language: csharp

dotnet: 3.0

solution: EventDispatcher.sln

jobs: 
  include:
    - stage: compile
      script:
        - dotnet restore
        - dotnet build
    - stage: test
      script:
        - dotnet test ./*Test*/*.csproj
    - stage: deploy
      script:
        - dotnet pack -c Release -p:EventDispatcher.nuspec
        - dotnet nuget push bin\Release\*.nupkg
          
stages:
  - compile
  - test
  - name: deploy
    if: branch = master

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
