language: csharp

dotnet: 3.0

solution: EventDispatcher.sln

script:
  - dotnet restore
  - dotnet build
  - dotnet test ./*Test*/.*.csproj

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
