language: csharp

dotnet:
  - 3.1

solution: EventDispatcher.sln

before_install:
  - sudo apt-get install -y dotnet-sdk-3.1

jobs:
  include:
    - stage: compile
      script:
        - dotnet restore
        - dotnet build
        - dotnet test ./*Test*/*.csproj
    - stage: deploy
      script:
        - dotnet build -c Release
        - dotnet pack ./GlobalElements.EventDispatcher/GlobalElements.EventDispatcher.csproj -c Release -p:NuspecFile=EventDispatcher.nuspec
        - dotnet nuget push ./GlobalElements.EventDispatcher/bin/Release/GlobalElements.EventDispatcher*.nupkg -s https://www.nuget.org -k ${NUGET_API_KEY}

stages:
  - compile
  - name: deploy
    if: (tag =~ ^v)

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
